# Example from https://github.com/redhat-developer-demos/docker-java/blob/devnexus2016/chapters/docker-compose.adoc
version: "2"

networks:
  mynet:

services:
  db:
    image: postgres
    container_name: "db"
    environment:
      POSTGRES_USER: ticketmonster
      POSTGRES_PASSWORD: ticketmonster-docker
    networks:
      - mynet
  mywildfly:
    image: rafabene/wildfly-ticketmonster
    networks:
      - mynet
    ports:
      - 8080
